import { RoleCategory, RoleCode, RoleScope } from "./types.js";
/**
 * Canonical role registry from Fan OS Global Role Registry (Section 2).
 * Permissions are NOT included — add via permission matrix in a later phase.
 */
export const ROLE_REGISTRY = {
    [RoleCode.PlatformSuperAdmin]: {
        code: RoleCode.PlatformSuperAdmin,
        name: "Platform Super Admin",
        description: "Tenant creation, global roles, production integrations, emergency access, full audit access.",
        scope: RoleScope.Platform,
        category: RoleCategory.Platform,
        primarySurfaces: ["Admin Web Console", "Operations Command Center"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.ClubAdmin]: {
        code: RoleCode.ClubAdmin,
        name: "Club Admin",
        description: "Club configuration, locations, staff users, module enablement, approval rules.",
        scope: RoleScope.Club,
        category: RoleCategory.Administration,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.ModuleAdmin]: {
        code: RoleCode.ModuleAdmin,
        name: "Module Admin",
        description: "Module configuration, module reports and role-scoped approvals.",
        scope: RoleScope.Module,
        category: RoleCategory.Administration,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.SecurityComplianceAdmin]: {
        code: RoleCode.SecurityComplianceAdmin,
        name: "Security & Compliance Admin",
        description: "LGPD controls, consent policy, DSAR, biometric governance, audit review.",
        scope: RoleScope.Privacy,
        category: RoleCategory.Security,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.Auditor]: {
        code: RoleCode.Auditor,
        name: "Auditor / Read-Only Reviewer",
        description: "Read audit logs, compliance reports and approved exports only.",
        scope: RoleScope.Audit,
        category: RoleCategory.Security,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.IntegrationDeveloper]: {
        code: RoleCode.IntegrationDeveloper,
        name: "Integration Developer",
        description: "API keys, webhooks, sandbox connectors, provider monitoring.",
        scope: RoleScope.Integration,
        category: RoleCategory.Platform,
        primarySurfaces: ["Admin Web Console", "Operations Command Center"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.ExecutiveViewer]: {
        code: RoleCode.ExecutiveViewer,
        name: "Executive Viewer",
        description: "Read KPIs, revenue, attendance, campaign and operational performance.",
        scope: RoleScope.Club,
        category: RoleCategory.Data,
        primarySurfaces: ["Operations Command Center", "Analytics Dashboard"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.FinanceManager]: {
        code: RoleCode.FinanceManager,
        name: "Finance Manager",
        description: "Refunds, reconciliation, settlement, fiscal documents and payout approval.",
        scope: RoleScope.Club,
        category: RoleCategory.Finance,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.SupportManager]: {
        code: RoleCode.SupportManager,
        name: "Support Manager",
        description: "Support queues, SLA rules, escalation policies and agent permissions.",
        scope: RoleScope.Club,
        category: RoleCategory.Support,
        primarySurfaces: ["Support Agent Console", "Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.SupportAgent]: {
        code: RoleCode.SupportAgent,
        name: "Support Agent",
        description: "Masked customer 360, ticket/order/loyalty lookup, support case handling.",
        scope: RoleScope.Club,
        category: RoleCategory.Support,
        primarySurfaces: ["Support Agent Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.CdpDataAnalyst]: {
        code: RoleCode.CdpDataAnalyst,
        name: "CDP / Data Analyst",
        description: "Event analysis, traits, segments, dashboards and permitted data exports.",
        scope: RoleScope.Club,
        category: RoleCategory.Data,
        primarySurfaces: ["Marketing & CDP Workspace"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.MarketingManager]: {
        code: RoleCode.MarketingManager,
        name: "Marketing Manager",
        description: "Templates, journeys, audience activation, attribution and channel sends.",
        scope: RoleScope.Club,
        category: RoleCategory.Marketing,
        primarySurfaces: ["Marketing & CDP Workspace"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.LoyaltyManager]: {
        code: RoleCode.LoyaltyManager,
        name: "Loyalty Manager",
        description: "Earn/redeem rules, tiers, rewards, coupons and points adjustment requests.",
        scope: RoleScope.Club,
        category: RoleCategory.Marketing,
        primarySurfaces: ["Admin Web Console", "Marketing & CDP Workspace"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.SponsorPartnerManager]: {
        code: RoleCode.SponsorPartnerManager,
        name: "Sponsor / Partner Manager",
        description: "Sponsor benefits, partner offers and sponsor performance reports.",
        scope: RoleScope.Club,
        category: RoleCategory.Marketing,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.TicketingManager]: {
        code: RoleCode.TicketingManager,
        name: "Ticketing Manager",
        description: "Events, seats, ticket products, pricing, inventory and check-in windows.",
        scope: RoleScope.Module,
        category: RoleCategory.Ticketing,
        primarySurfaces: ["Admin Web Console", "Ticketing/Event Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.MembershipManager]: {
        code: RoleCode.MembershipManager,
        name: "Membership Manager",
        description: "Membership tiers, benefits, priority windows and entitlement rules.",
        scope: RoleScope.Module,
        category: RoleCategory.Ticketing,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.BoxOfficeOperator]: {
        code: RoleCode.BoxOfficeOperator,
        name: "Box Office Operator",
        description: "Sell/reserve/transfer/cancel tickets within assigned limits.",
        scope: RoleScope.Location,
        category: RoleCategory.Ticketing,
        primarySurfaces: ["Box Office"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.GateSupervisor]: {
        code: RoleCode.GateSupervisor,
        name: "Gate Supervisor",
        description: "Gate monitoring, manual override approval and incident escalation.",
        scope: RoleScope.Location,
        category: RoleCategory.Operations,
        primarySurfaces: ["Gate Access App", "Operations Command Center"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.GateOperator]: {
        code: RoleCode.GateOperator,
        name: "Gate Operator",
        description: "Validate entry and see allowed/denied status only.",
        scope: RoleScope.Location,
        category: RoleCategory.Operations,
        primarySurfaces: ["Gate Access App"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.RetailManager]: {
        code: RoleCode.RetailManager,
        name: "Retail Manager",
        description: "Catalog, pricing, store setup, stock policies, transfers and reports.",
        scope: RoleScope.Module,
        category: RoleCategory.Commerce,
        primarySurfaces: ["Admin Web Console", "Retail POS App"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.StoreManager]: {
        code: RoleCode.StoreManager,
        name: "Store Manager",
        description: "Local stock counts, staff shifts, returns and location reports.",
        scope: RoleScope.Location,
        category: RoleCategory.Commerce,
        primarySurfaces: ["Retail POS App", "Warehouse Terminal"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.PosCashier]: {
        code: RoleCode.PosCashier,
        name: "POS Cashier",
        description: "Sales, returns within limit, fan attach and payment capture.",
        scope: RoleScope.Location,
        category: RoleCategory.Commerce,
        primarySurfaces: ["Retail POS App", "F&B POS App"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.WarehouseInventoryManager]: {
        code: RoleCode.WarehouseInventoryManager,
        name: "Warehouse / Inventory Manager",
        description: "Receiving, transfers, stock counts, adjustments and replenishment.",
        scope: RoleScope.Location,
        category: RoleCategory.Commerce,
        primarySurfaces: ["Warehouse / Inventory Terminal"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.FbManager]: {
        code: RoleCode.FbManager,
        name: "F&B Manager",
        description: "Menus, recipes, stands, event availability and stock planning.",
        scope: RoleScope.Module,
        category: RoleCategory.Commerce,
        primarySurfaces: ["Admin Web Console", "F&B POS App"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.StandManager]: {
        code: RoleCode.StandManager,
        name: "Stand Manager",
        description: "Stand stock, replenishment, shift status and local refund approval.",
        scope: RoleScope.Location,
        category: RoleCategory.Commerce,
        primarySurfaces: ["F&B POS App"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.KitchenPrepStaff]: {
        code: RoleCode.KitchenPrepStaff,
        name: "Kitchen / Prep Staff",
        description: "Accept, prepare and mark orders ready/picked up.",
        scope: RoleScope.Location,
        category: RoleCategory.Commerce,
        primarySurfaces: ["Kitchen Display"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.MarketplaceManager]: {
        code: RoleCode.MarketplaceManager,
        name: "Marketplace Manager",
        description: "Vendor approvals, commissions, disputes and product approvals.",
        scope: RoleScope.Module,
        category: RoleCategory.Marketplace,
        primarySurfaces: ["Admin Web Console"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.VendorAdmin]: {
        code: RoleCode.VendorAdmin,
        name: "Vendor Admin",
        description: "Own catalog, orders, fulfillment, dispute responses and payout view.",
        scope: RoleScope.Vendor,
        category: RoleCategory.Marketplace,
        primarySurfaces: ["Vendor Portal"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.VendorStaff]: {
        code: RoleCode.VendorStaff,
        name: "Vendor Staff",
        description: "Own catalog, orders, fulfillment within assigned vendor.",
        scope: RoleScope.Vendor,
        category: RoleCategory.Marketplace,
        primarySurfaces: ["Vendor Portal"],
        isStaff: true,
        isSystem: true,
    },
    [RoleCode.FanMember]: {
        code: RoleCode.FanMember,
        name: "Fan / Member",
        description: "Own profile, tickets, orders, wallet, rewards, consent and support chat.",
        scope: RoleScope.Self,
        category: RoleCategory.Fan,
        primarySurfaces: ["Fan Mobile App / PWA", "Fan Web Portal"],
        isStaff: false,
        isSystem: true,
    },
};
/** All registered role codes */
export const ALL_ROLE_CODES = Object.values(RoleCode);
/** Staff-only roles (excludes Fan/Member) */
export const STAFF_ROLE_CODES = ALL_ROLE_CODES.filter((code) => ROLE_REGISTRY[code].isStaff);
/** Default seed roles for single-club MVP bootstrap */
export const MVP_SEED_ROLE_CODES = [
    RoleCode.PlatformSuperAdmin,
    RoleCode.ClubAdmin,
    RoleCode.ModuleAdmin,
    RoleCode.SecurityComplianceAdmin,
    RoleCode.SupportAgent,
    RoleCode.FanMember,
];
//# sourceMappingURL=roles.js.map