/**
 * Frontend mirror of the @coxa/rbac ROLE_REGISTRY.
 * Keeps the full role list without requiring a Node build — safe to import in Vite.
 *
 * Each entry maps directly to RoleCode values from @coxa/rbac/src/types.js.
 */

export const ROLE_REGISTRY = {
  platform_super_admin: {
    code: "platform_super_admin",
    name: "Platform Super Admin",
    description: "Tenant creation, global roles, production integrations, emergency access, full audit access.",
    scope: "platform",
    category: "platform",
    surfaces: ["Admin Console", "Operations Center"],
  },
  club_admin: {
    code: "club_admin",
    name: "Club Admin",
    description: "Club configuration, locations, staff users, module enablement, approval rules.",
    scope: "club",
    category: "administration",
    surfaces: ["Admin Console"],
  },
  module_admin: {
    code: "module_admin",
    name: "Module Admin",
    description: "Module configuration, module reports and role-scoped approvals.",
    scope: "module",
    category: "administration",
    surfaces: ["Admin Console"],
  },
  security_compliance_admin: {
    code: "security_compliance_admin",
    name: "Security & Compliance Admin",
    description: "LGPD controls, consent policy, DSAR, biometric governance, audit review.",
    scope: "privacy",
    category: "security",
    surfaces: ["Admin Console"],
  },
  auditor: {
    code: "auditor",
    name: "Auditor / Read-Only Reviewer",
    description: "Read audit logs, compliance reports and approved exports only.",
    scope: "audit",
    category: "security",
    surfaces: ["Admin Console"],
  },
  integration_developer: {
    code: "integration_developer",
    name: "Integration Developer",
    description: "API keys, webhooks, sandbox connectors, provider monitoring.",
    scope: "integration",
    category: "platform",
    surfaces: ["Admin Console", "Operations Center"],
  },
  executive_viewer: {
    code: "executive_viewer",
    name: "Executive Viewer",
    description: "Read KPIs, revenue, attendance, campaign and operational performance.",
    scope: "club",
    category: "data",
    surfaces: ["Operations Center", "Analytics Dashboard"],
  },
  finance_manager: {
    code: "finance_manager",
    name: "Finance Manager",
    description: "Refunds, reconciliation, settlement, fiscal documents and payout approval.",
    scope: "club",
    category: "finance",
    surfaces: ["Admin Console"],
  },
  support_manager: {
    code: "support_manager",
    name: "Support Manager",
    description: "Support queues, SLA rules, escalation policies and agent permissions.",
    scope: "club",
    category: "support",
    surfaces: ["Support Console", "Admin Console"],
  },
  support_agent: {
    code: "support_agent",
    name: "Support Agent",
    description: "Masked customer 360, ticket/order/loyalty lookup, support case handling.",
    scope: "club",
    category: "support",
    surfaces: ["Support Console"],
  },
  cdp_data_analyst: {
    code: "cdp_data_analyst",
    name: "CDP / Data Analyst",
    description: "Event analysis, traits, segments, dashboards and permitted data exports.",
    scope: "club",
    category: "data",
    surfaces: ["Marketing & CDP Workspace"],
  },
  marketing_manager: {
    code: "marketing_manager",
    name: "Marketing Manager",
    description: "Templates, journeys, audience activation, attribution and channel sends.",
    scope: "club",
    category: "marketing",
    surfaces: ["Marketing & CDP Workspace"],
  },
  loyalty_manager: {
    code: "loyalty_manager",
    name: "Loyalty Manager",
    description: "Earn/redeem rules, tiers, rewards, coupons and points adjustment requests.",
    scope: "club",
    category: "marketing",
    surfaces: ["Admin Console", "Marketing & CDP Workspace"],
  },
  sponsor_partner_manager: {
    code: "sponsor_partner_manager",
    name: "Sponsor / Partner Manager",
    description: "Sponsor benefits, partner offers and sponsor performance reports.",
    scope: "club",
    category: "marketing",
    surfaces: ["Admin Console"],
  },
  ticketing_manager: {
    code: "ticketing_manager",
    name: "Ticketing Manager",
    description: "Events, seats, ticket products, pricing, inventory and check-in windows.",
    scope: "module",
    category: "ticketing",
    surfaces: ["Admin Console", "Ticketing Console"],
  },
  membership_manager: {
    code: "membership_manager",
    name: "Membership Manager",
    description: "Membership tiers, benefits, priority windows and entitlement rules.",
    scope: "module",
    category: "ticketing",
    surfaces: ["Admin Console"],
  },
  box_office_operator: {
    code: "box_office_operator",
    name: "Box Office Operator",
    description: "Sell/reserve/transfer/cancel tickets within assigned limits.",
    scope: "location",
    category: "ticketing",
    surfaces: ["Box Office"],
  },
  gate_supervisor: {
    code: "gate_supervisor",
    name: "Gate Supervisor",
    description: "Gate monitoring, manual override approval and incident escalation.",
    scope: "location",
    category: "operations",
    surfaces: ["Gate Access App", "Operations Center"],
  },
  gate_operator: {
    code: "gate_operator",
    name: "Gate Operator",
    description: "Validate entry and see allowed/denied status only.",
    scope: "location",
    category: "operations",
    surfaces: ["Gate Access App"],
  },
  retail_manager: {
    code: "retail_manager",
    name: "Retail Manager",
    description: "Catalog, pricing, store setup, stock policies, transfers and reports.",
    scope: "module",
    category: "commerce",
    surfaces: ["Admin Console", "Retail POS"],
  },
  store_manager: {
    code: "store_manager",
    name: "Store Manager",
    description: "Local stock counts, staff shifts, returns and location reports.",
    scope: "location",
    category: "commerce",
    surfaces: ["Retail POS", "Warehouse Terminal"],
  },
  pos_cashier: {
    code: "pos_cashier",
    name: "POS Cashier",
    description: "Sales, returns within limit, fan attach and payment capture.",
    scope: "location",
    category: "commerce",
    surfaces: ["Retail POS", "F&B POS"],
  },
  warehouse_inventory_manager: {
    code: "warehouse_inventory_manager",
    name: "Warehouse / Inventory Manager",
    description: "Receiving, transfers, stock counts, adjustments and replenishment.",
    scope: "location",
    category: "commerce",
    surfaces: ["Warehouse Terminal"],
  },
  fb_manager: {
    code: "fb_manager",
    name: "F&B Manager",
    description: "Menus, recipes, stands, event availability and stock planning.",
    scope: "module",
    category: "commerce",
    surfaces: ["Admin Console", "F&B POS"],
  },
  stand_manager: {
    code: "stand_manager",
    name: "Stand Manager",
    description: "Stand stock, replenishment, shift status and local refund approval.",
    scope: "location",
    category: "commerce",
    surfaces: ["F&B POS"],
  },
  kitchen_prep_staff: {
    code: "kitchen_prep_staff",
    name: "Kitchen / Prep Staff",
    description: "Accept, prepare and mark orders ready/picked up.",
    scope: "location",
    category: "commerce",
    surfaces: ["Kitchen Display"],
  },
  marketplace_manager: {
    code: "marketplace_manager",
    name: "Marketplace Manager",
    description: "Vendor approvals, commissions, disputes and product approvals.",
    scope: "module",
    category: "marketplace",
    surfaces: ["Admin Console"],
  },
  vendor_admin: {
    code: "vendor_admin",
    name: "Vendor Admin",
    description: "Own catalog, orders, fulfillment, dispute responses and payout view.",
    scope: "vendor",
    category: "marketplace",
    surfaces: ["Vendor Portal"],
  },
  vendor_staff: {
    code: "vendor_staff",
    name: "Vendor Staff",
    description: "Own catalog, orders, fulfillment within assigned vendor.",
    scope: "vendor",
    category: "marketplace",
    surfaces: ["Vendor Portal"],
  },
  fan_member: {
    code: "fan_member",
    name: "Fan / Member",
    description: "Own profile, tickets, orders, wallet, rewards, consent and support chat.",
    scope: "self",
    category: "fan",
    surfaces: ["Fan Mobile App", "Fan Web Portal"],
  },
};

/**
 * Ordered list of categories shown in the Role Registry and picker tabs.
 * Maps to RoleCategory values and provides a human-readable label + color.
 */
export const ROLE_CATEGORIES = [
  { key: "administration", label: "Administration",  color: "#3b82f6" },
  { key: "ticketing",      label: "Ticketing",       color: "#f97316" },
  { key: "operations",     label: "Operations",      color: "#fb923c" },
  { key: "commerce",       label: "Commerce",        color: "#14b8a6" },
  { key: "marketing",      label: "Marketing",       color: "#ec4899" },
  { key: "data",           label: "Data / Analytics",color: "#8b5cf6" },
  { key: "support",        label: "Support",         color: "#eab308" },
  { key: "finance",        label: "Finance",         color: "#22c55e" },
  { key: "marketplace",    label: "Marketplace",     color: "#06b6d4" },
  { key: "security",       label: "Security",        color: "#ef4444" },
  { key: "platform",       label: "Platform",        color: "#6b7280" },
];

/** Module access granted per role — mirrors permissions.js ROLE_MODULE_MAP */
export const ROLE_MODULE_LABELS = {
  platform_super_admin:       ["Admin", "Retail", "F&B", "Ticketing", "CDP", "Personalization", "Loyalty", "Support"],
  club_admin:                  ["Admin", "Retail", "F&B", "Ticketing", "CDP", "Personalization", "Loyalty", "Support"],
  module_admin:                ["Admin", "Retail", "F&B", "Ticketing", "CDP", "Personalization", "Loyalty", "Support"],
  security_compliance_admin:   ["Admin"],
  auditor:                     ["Admin"],
  integration_developer:       ["Admin"],
  executive_viewer:            ["Retail", "F&B", "Ticketing", "CDP"],
  finance_manager:             ["Retail", "F&B", "Ticketing"],
  support_manager:             ["Support", "CDP", "Admin"],
  support_agent:               ["Support", "CDP"],
  cdp_data_analyst:            ["CDP", "Personalization"],
  marketing_manager:           ["CDP", "Personalization", "Loyalty"],
  loyalty_manager:             ["Loyalty", "CDP"],
  sponsor_partner_manager:     ["Admin"],
  ticketing_manager:           ["Ticketing", "Support"],
  membership_manager:          ["Ticketing"],
  box_office_operator:         ["Ticketing"],
  gate_supervisor:             ["Ticketing", "Support"],
  gate_operator:               ["Ticketing"],
  retail_manager:              ["Retail", "Admin"],
  store_manager:               ["Retail"],
  pos_cashier:                 ["Retail", "F&B"],
  warehouse_inventory_manager: ["Retail"],
  fb_manager:                  ["F&B", "Retail"],
  stand_manager:               ["F&B"],
  kitchen_prep_staff:          ["F&B"],
  marketplace_manager:         ["Marketplace"],
  vendor_admin:                ["Marketplace"],
  vendor_staff:                ["Marketplace"],
  fan_member:                  [],
};
